name: kanjad
description: "L'application de e-commerce Number 1."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # Removed Firebase dependencies
  supabase_flutter: ^2.8.3
  fluentui_system_icons: ^1.1.273
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.3.9
  shared_preferences: ^2.5.3
  web: ^1.1.1
  carousel_slider: ^5.1.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  pdf: ^3.11.0
  printing: ^5.13.4
  cinetpay: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.6.1
  provider: ^6.1.2
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.2
  video_player: ^2.10.0
  uuid: ^4.4.0
  async: ^2.13.0
  dotted_border: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  assets:
    - .env
    - assets/images/kanjad.png
  uses-material-design: true