import 'package:supabase_flutter/supabase_flutter.dart';

class SupabaseTableInitializer {
  static Future<void> initializeTables() async {
    final client = Supabase.instance.client;
    
    try {
      // Création de la table utilisateurs
      await client.rpc('execute_sql', params: {
        'sql': '''
          CREATE TABLE IF NOT EXISTS utilisateurs (
            id UUID PRIMARY KEY REFERENCES auth.users(id),
            nomutilisateur TEXT,
            prenomutilisateur TEXT,
            emailutilisateur TEXT UNIQUE,
            numeroutilisateur TEXT,
            villeutilisateur TEXT,
            roleutilisateur TEXT
          );
        '''
      });
      
      // Création de la table categories
      await client.rpc('execute_sql', params: {
        'sql': '''
          CREATE TABLE IF NOT EXISTS categories (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nomcategorie TEXT,
            description TEXT
          );
        '''
      });
      
      // Création de la table produits
      await client.rpc('execute_sql', params: {
        'sql': '''
          CREATE TABLE IF NOT EXISTS produits (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nomproduit TEXT,
            description TEXT,
            descriptioncourte TEXT,
            prix TEXT,
            ancientprix TEXT,
            vues TEXT,
            modele TEXT,
            marque TEXT,
            categorie TEXT,
            type TEXT,
            souscategorie TEXT,
            jeveut BOOLEAN,
            aupanier BOOLEAN,
            img1 TEXT,
            img2 TEXT,
            img3 TEXT,
            cash BOOLEAN,
            electronique BOOLEAN,
            enstock BOOLEAN,
            quantite TEXT,
            livrable BOOLEAN,
            enpromo BOOLEAN,
            methodelivraison TEXT
          );
        '''
      });
      
      // Création de la table commandes
      await client.rpc('execute_sql', params: {
        'sql': '''
          CREATE TABLE IF NOT EXISTS commandes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            idutilisateur UUID REFERENCES utilisateurs(id),
            datecommande TEXT,
            montanttotal TEXT,
            statutpaiement TEXT,
            adresselivraison TEXT,
            numerocommande TEXT
          );
        '''
      });
      
      // Création de la table factures
      await client.rpc('execute_sql', params: {
        'sql': '''
          CREATE TABLE IF NOT EXISTS factures (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            idcommande BIGINT REFERENCES commandes(id),
            datefacture TEXT,
            montantfacture TEXT,
            statutfacture TEXT
          );
        '''
      });
      
      // Création de la table paniers
      await client.rpc('execute_sql', params: {
        'sql': '''
          CREATE TABLE IF NOT EXISTS paniers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            idutilisateur UUID REFERENCES utilisateurs(id),
            idproduit BIGINT REFERENCES produits(id),
            quantite INTEGER
          );
        '''
      });
      
      // Création de la table souhaits
      await client.rpc('execute_sql', params: {
        'sql': '''
          CREATE TABLE IF NOT EXISTS souhaits (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            idutilisateur UUID REFERENCES utilisateurs(id),
            idproduit BIGINT REFERENCES produits(id)
          );
        '''
      });
      
      // Création de la table messages
      await client.rpc('execute_sql', params: {
        'sql': '''
          CREATE TABLE IF NOT EXISTS messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            idutilisateur UUID REFERENCES utilisateurs(id),
            contenu TEXT,
            timestamp TEXT,
            idconversation TEXT
          );
        '''
      });
      
      print('Toutes les tables ont été créées avec succès');
    } catch (e) {
      print('Erreur lors de la création des tables: $e');
      rethrow;
    }
  }
}